micronaut:
  application:
    name: kafka
  metrics:
    enabled: true
    export:
      jmx:
        enabled: true
        step: PT1M
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
netty:
  default:
    allocator:
      max-order: 3
otel:
  traces:
    exporter: logging
